# --- Gen1 Flat Wagon ----------------------------------------------------------

GEN1_FLAT_WAGON_FILES = \
	$(BUILD_DIR)/gfx/Gen1_Flat_Wagon_Crates.png \
	$(BUILD_DIR)/gfx/Gen1_Flat_Wagon_Planks.png \
	$(BUILD_DIR)/gfx/Gen1_Flat_Wagon_Wood.png \
	$(BUILD_DIR)/gfx/Gen1_Flat_Wagon_Steel.png \
	$(BUILD_DIR)/gfx/Gen1_Flat_Wagon_Horse.png

$(BUILD_DIR)/gfx/Gen1/Flat_Wagon/%_1x3.png: gfx/Wagons/Gen1/Flat_Wagon/%.png
	@echo [GFX] $@
	@$(PYTHON) tools/concat.py --output $@ --axis 1 $< $< $<

$(BUILD_DIR)/gfx/Gen1/Flat_Wagon/Cargo/%_4x1.png: gfx/Wagons/Gen1/Flat_Wagon/Cargo/%.png
	@echo [GFX] $@
	@$(PYTHON) tools/concat.py --output $@ --axis 0 $< $< $< $<

$(BUILD_DIR)/gfx/Gen1_Flat_Wagon_%.png: $(BUILD_DIR)/gfx/Gen1/Flat_Wagon/Layer1_1x3.png $(BUILD_DIR)/gfx/Gen1/Flat_Wagon/Cargo/%_4x1.png $(BUILD_DIR)/gfx/Gen1/Flat_Wagon/Layer2_1x3.png
	@echo [GFX] $@
	@$(PYTHON) tools/stack.py --output $@ $^


# --- Gen1 Open Wagon ----------------------------------------------------------

GEN1_OPEN_WAGON_FILES = \
	$(BUILD_DIR)/gfx/Gen1_Open_Wagon_Bauxite.png \
	$(BUILD_DIR)/gfx/Gen1_Open_Wagon_Coal.png \
	$(BUILD_DIR)/gfx/Gen1_Open_Wagon_Gravel.png \
	$(BUILD_DIR)/gfx/Gen1_Open_Wagon_Ore.png \
	$(BUILD_DIR)/gfx/Gen1_Open_Wagon_Salt.png \
	$(BUILD_DIR)/gfx/Gen1_Open_Wagon_Sand.png \
	$(BUILD_DIR)/gfx/Gen1_Open_Wagon_Lemons.png \
	$(BUILD_DIR)/gfx/Gen1_Open_Wagon_Beans.png

$(BUILD_DIR)/gfx/Gen1/Open_Wagon/%_1x3.png: gfx/Wagons/Gen1/Open_Wagon/%.png
	@echo [GFX] $@
	@$(PYTHON) tools/concat.py --output $@ --axis 1 $< $< $<

$(BUILD_DIR)/gfx/Gen1/Open_Wagon/Cargo/%_4x1.png: gfx/Wagons/Gen1/Open_Wagon/Cargo/%.png
	@echo [GFX] $@
	@$(PYTHON) tools/concat.py --output $@ --axis 0 $< $< $< $<

$(BUILD_DIR)/gfx/Gen1_Open_Wagon_%.png: $(BUILD_DIR)/gfx/Gen1/Open_Wagon/Layer1_1x3.png $(BUILD_DIR)/gfx/Gen1/Open_Wagon/Cargo/%_4x1.png # $(BUILD_DIR)/gfx/Gen1/Flat_Wagon/Layer2_1x3.png
	@echo [GFX] $@
	@$(PYTHON) tools/stack.py --output $@ $^


# --- Gen1 Boxcar --------------------------------------------------------------

GEN1_BOXCAR_FILES = \
	$(BUILD_DIR)/gfx/Gen1_Boxcar_Standard.png

$(BUILD_DIR)/gfx/Gen1/Boxcar/%_1x3.png: gfx/Wagons/Gen1/Boxcar/%.png
	@echo [GFX] $@
	@$(PYTHON) tools/concat.py --output $@ --axis 1 $< $< $<

$(BUILD_DIR)/gfx/Gen1_Boxcar_%.png: $(BUILD_DIR)/gfx/Gen1/Boxcar/%_1x3.png
	@echo [GFX] $@
	@$(PYTHON) tools/stack.py --output $@ $^


# --- Gen1 Tanker --------------------------------------------------------------

GEN1_TANKER_FILES = \
	$(BUILD_DIR)/gfx/Gen1_Tanker_Standard.png

$(BUILD_DIR)/gfx/Gen1/Tanker/%_1x3.png: gfx/Wagons/Gen1/Tanker/%.png
	@echo [GFX] $@
	@$(PYTHON) tools/concat.py --output $@ --axis 1 $< $< $<

$(BUILD_DIR)/gfx/Gen1_Tanker_%.png: $(BUILD_DIR)/gfx/Gen1/Tanker/%_1x3.png
	@echo [GFX] $@
	@$(PYTHON) tools/stack.py --output $@ $^


# --- Gen2 Flat Wagon ----------------------------------------------------------

GEN2_FLAT_WAGON_FILES = \
	$(BUILD_DIR)/gfx/Gen2_Flat_Wagon_Barrels.png     \
	$(BUILD_DIR)/gfx/Gen2_Flat_Wagon_Crates.png      \
	$(BUILD_DIR)/gfx/Gen2_Flat_Wagon_Copper.png      \
	$(BUILD_DIR)/gfx/Gen2_Flat_Wagon_Planks.png      \
	$(BUILD_DIR)/gfx/Gen2_Flat_Wagon_Wood.png        \
	$(BUILD_DIR)/gfx/Gen2_Flat_Wagon_Paper.png       \
	$(BUILD_DIR)/gfx/Gen2_Flat_Wagon_Machinery.png   \
	$(BUILD_DIR)/gfx/Gen2_Flat_Wagon_Tyres.png       \
	$(BUILD_DIR)/gfx/Gen2_Flat_Wagon_Steel_Wire.png  \
	$(BUILD_DIR)/gfx/Gen2_Flat_Wagon_Steel_Coil.png  \
	$(BUILD_DIR)/gfx/Gen2_Flat_Wagon_Steel_Sheets.png 

$(BUILD_DIR)/gfx/Gen2/Flat_Wagon/%_1x3.png: gfx/Wagons/Gen2/Flat_Wagon/%.png
	@echo [GFX] $@
	@$(PYTHON) tools/concat.py --output $@ --axis 1 $< $< $<

$(BUILD_DIR)/gfx/Gen2/Flat_Wagon/Cargo/%_4x1.png: gfx/Wagons/Gen2/Flat_Wagon/Cargo/%.png
	@echo [GFX] $@
	@$(PYTHON) tools/concat.py --output $@ --axis 0 $< $< $< $<

$(BUILD_DIR)/gfx/Gen2_Flat_Wagon_%.png: $(BUILD_DIR)/gfx/Gen2/Flat_Wagon/Layer1_1x3.png $(BUILD_DIR)/gfx/Gen2/Flat_Wagon/Cargo/%_4x1.png $(BUILD_DIR)/gfx/Gen2/Flat_Wagon/Layer2_1x3.png
	@echo [GFX] $@
	@$(PYTHON) tools/stack.py --output $@ $^

# --- Gen2 Open Wagon ----------------------------------------------------------

GEN2_OPEN_WAGON_FILES = \
	$(BUILD_DIR)/gfx/Gen2_Open_Wagon_Biomass.png \
	$(BUILD_DIR)/gfx/Gen2_Open_Wagon_Bauxite.png \
	$(BUILD_DIR)/gfx/Gen2_Open_Wagon_Beans.png \
	$(BUILD_DIR)/gfx/Gen2_Open_Wagon_Coal.png \
	$(BUILD_DIR)/gfx/Gen2_Open_Wagon_Copper_Ore.png \
	$(BUILD_DIR)/gfx/Gen2_Open_Wagon_Crates.png \
	$(BUILD_DIR)/gfx/Gen2_Open_Wagon_Gravel.png \
	$(BUILD_DIR)/gfx/Gen2_Open_Wagon_Maize.png \
	$(BUILD_DIR)/gfx/Gen2_Open_Wagon_Nickel.png \
	$(BUILD_DIR)/gfx/Gen2_Open_Wagon_Oranges.png \
	$(BUILD_DIR)/gfx/Gen2_Open_Wagon_Ore.png \
	$(BUILD_DIR)/gfx/Gen2_Open_Wagon_Peat.png \
	$(BUILD_DIR)/gfx/Gen2_Open_Wagon_Salt.png \
	$(BUILD_DIR)/gfx/Gen2_Open_Wagon_Sand.png \
	$(BUILD_DIR)/gfx/Gen2_Open_Wagon_Scrap_Metal.png \
	$(BUILD_DIR)/gfx/Gen2_Open_Wagon_Wood.png \

$(BUILD_DIR)/gfx/Gen2/Open_Wagon/%_1x3.png: gfx/Wagons/Gen2/Open_Wagon/%.png
	@echo [GFX] $@
	@$(PYTHON) tools/concat.py --output $@ --axis 1 $< $< $<

$(BUILD_DIR)/gfx/Gen2/Open_Wagon/Cargo/%_4x1.png: gfx/Wagons/Gen2/Open_Wagon/Cargo/%.png
	@echo [GFX] $@
	@$(PYTHON) tools/concat.py --output $@ --axis 0 $< $< $< $<

$(BUILD_DIR)/gfx/Gen2_Open_Wagon_%.png: $(BUILD_DIR)/gfx/Gen2/Open_Wagon/Layer1_1x3.png $(BUILD_DIR)/gfx/Gen2/Open_Wagon/Cargo/%_4x1.png # $(BUILD_DIR)/gfx/Gen1/Flat_Wagon/Layer2_1x3.png
	@echo [GFX] $@
	@$(PYTHON) tools/stack.py --output $@ $^

# --- Gen2 Lidded Wagon --------------------------------------------------------

GEN2_LIDDED_WAGON_FILES = \
	$(BUILD_DIR)/gfx/Gen2_Lidded_Wagon_Biomass.png \
	$(BUILD_DIR)/gfx/Gen2_Lidded_Wagon_Carbon.png \
	$(BUILD_DIR)/gfx/Gen2_Lidded_Wagon_Cement.png \
	$(BUILD_DIR)/gfx/Gen2_Lidded_Wagon_Clay.png \
	$(BUILD_DIR)/gfx/Gen2_Lidded_Wagon_Grain.png \
	$(BUILD_DIR)/gfx/Gen2_Lidded_Wagon_Limestone.png \
	$(BUILD_DIR)/gfx/Gen2_Lidded_Wagon_Nitrate.png \
	$(BUILD_DIR)/gfx/Gen2_Lidded_Wagon_Potash.png \
	$(BUILD_DIR)/gfx/Gen2_Lidded_Wagon_Salt.png

$(BUILD_DIR)/gfx/Gen2/Lidded_Wagon/Layer1.png: gfx/Wagons/Gen2/Lidded_Wagon/Open.png gfx/Wagons/Gen2/Lidded_Wagon/Closed.png
	@echo [GFX] $@
	@$(PYTHON) tools/concat.py --output $@ --axis 1 $< $< $^

$(BUILD_DIR)/gfx/Gen2/Lidded_Wagon/%_4x1.png: gfx/Wagons/Gen2/Lidded_Wagon/Cargo/%.png
	@echo [GFX] $@
	@$(PYTHON) tools/concat.py --output $@ --axis 0 $< $< $< $<

$(BUILD_DIR)/gfx/Gen2_Lidded_Wagon_%.png: $(BUILD_DIR)/gfx/Gen2/Lidded_Wagon/Layer1.png gfx/Wagons/Gen2/Lidded_Wagon/Cargo/%.png
	@echo [GFX] $@
	@$(PYTHON) tools/stack.py --output $@ $^

# --- Gen2 Boxcar --------------------------------------------------------------

GEN2_BOXCAR_FILES = \
	$(BUILD_DIR)/gfx/Gen2_Boxcar_Standard.png

$(BUILD_DIR)/gfx/Gen2/Boxcar/Standard.png: gfx/Wagons/Gen2/Boxcar/Standard/Closed.png gfx/Wagons/Gen2/Boxcar/Standard/Open.png
	@echo [GFX] $@
	@$(PYTHON) tools/concat.py --output $@ --axis 1 $< $^

$(BUILD_DIR)/gfx/Gen2_Boxcar_%.png: $(BUILD_DIR)/gfx/Gen2/Boxcar/%.png
	@echo [GFX] $@
	@$(PYTHON) tools/stack.py --output $@ $^

# --- Gen2 Tanker --------------------------------------------------------------

GEN2_TANKER_FILES = \
	$(BUILD_DIR)/gfx/Gen2_Tanker_Acid.png \
	$(BUILD_DIR)/gfx/Gen2_Tanker_CC1.png \
	$(BUILD_DIR)/gfx/Gen2_Tanker_CC2.png \
	$(BUILD_DIR)/gfx/Gen2_Tanker_Fuel.png \
	$(BUILD_DIR)/gfx/Gen2_Tanker_Milk.png \
	$(BUILD_DIR)/gfx/Gen2_Tanker_Oil.png \
	$(BUILD_DIR)/gfx/Gen2_Tanker_Wine.png \

$(BUILD_DIR)/gfx/Gen2/Tanker/Cargo/%_4x1.png: gfx/Wagons/Gen2/Tanker/Cargo/%.png
	@echo [GFX] $@
	@$(PYTHON) tools/concat.py --output $@ --axis 0 $< $< $< $<

$(BUILD_DIR)/gfx/Gen2_Tanker_%.png: gfx/Wagons/Gen2/Tanker/Layer1.png $(BUILD_DIR)/gfx/Gen2/Tanker/Cargo/%_4x1.png gfx/Wagons/Gen2/Tanker/Layer2.png
	@echo [GFX] $@
	@$(PYTHON) tools/stack.py --output $@ $^

# --- Gen3 Flat Wagon ----------------------------------------------------------

GEN3_FLAT_WAGON_FILES = \
	$(BUILD_DIR)/gfx/Gen3_Flat_Wagon_Crates.png	\
	$(BUILD_DIR)/gfx/Gen3_Flat_Wagon_Explosives.png	\
	$(BUILD_DIR)/gfx/Gen3_Flat_Wagon_Planks.png	\
	$(BUILD_DIR)/gfx/Gen3_Flat_Wagon_Steel_Sheets.png	\
	$(BUILD_DIR)/gfx/Gen3_Flat_Wagon_Tractor.png	\
	$(BUILD_DIR)/gfx/Gen3_Flat_Wagon_Wood.png	\

$(BUILD_DIR)/gfx/Gen3/Flat_Wagon/%_1x3.png: gfx/Wagons/Gen3/Flat_Wagon/%.png
	@echo [GFX] $@
	@$(PYTHON) tools/concat.py --output $@ --axis 1 $< $< $<

$(BUILD_DIR)/gfx/Gen3/Flat_Wagon/Cargo/%_4x1.png: gfx/Wagons/Gen3/Flat_Wagon/Cargo/%.png
	@echo [GFX] $@
	@$(PYTHON) tools/concat.py --output $@ --axis 0 $< $< $< $<

$(BUILD_DIR)/gfx/Gen3_Flat_Wagon_%.png: $(BUILD_DIR)/gfx/Gen3/Flat_Wagon/Layer1_1x3.png $(BUILD_DIR)/gfx/Gen3/Flat_Wagon/Cargo/%_4x1.png #$(BUILD_DIR)/gfx/Gen3/Flat_Wagon/Layer2_1x3.png
	@echo [GFX] $@
	@$(PYTHON) tools/stack.py --output $@ $^

# --- Gen3 Open Wagon ----------------------------------------------------------

GEN3_OPEN_WAGON_FILES = \
	$(BUILD_DIR)/gfx/Gen3_Open_Wagon_Biomass.png \
	$(BUILD_DIR)/gfx/Gen3_Open_Wagon_Bauxite.png \
	$(BUILD_DIR)/gfx/Gen3_Open_Wagon_Beans.png \
	$(BUILD_DIR)/gfx/Gen3_Open_Wagon_Coal.png \
	$(BUILD_DIR)/gfx/Gen3_Open_Wagon_Copper_Ore.png \
	$(BUILD_DIR)/gfx/Gen3_Open_Wagon_Gravel.png \
	$(BUILD_DIR)/gfx/Gen3_Open_Wagon_Lemons.png \
	$(BUILD_DIR)/gfx/Gen3_Open_Wagon_Maize.png \
	$(BUILD_DIR)/gfx/Gen3_Open_Wagon_Nickel.png \
	$(BUILD_DIR)/gfx/Gen3_Open_Wagon_Ore.png \
	$(BUILD_DIR)/gfx/Gen3_Open_Wagon_Salt.png \
	$(BUILD_DIR)/gfx/Gen3_Open_Wagon_Sand.png \
	$(BUILD_DIR)/gfx/Gen3_Open_Wagon_Scrap_Metal.png \
	$(BUILD_DIR)/gfx/Gen3_Open_Wagon_Wood.png \

$(BUILD_DIR)/gfx/Gen3/Open_Wagon/%_1x3.png: gfx/Wagons/Gen3/Open_Wagon/%.png
	@echo [GFX] $@
	@$(PYTHON) tools/concat.py --output $@ --axis 1 $< $< $<

$(BUILD_DIR)/gfx/Gen3/Open_Wagon/Cargo/%_4x1.png: gfx/Wagons/Gen3/Open_Wagon/Cargo/%.png
	@echo [GFX] $@
	@$(PYTHON) tools/concat.py --output $@ --axis 0 $< $< $< $<

$(BUILD_DIR)/gfx/Gen3_Open_Wagon_%.png: $(BUILD_DIR)/gfx/Gen3/Open_Wagon/Layer1_1x3.png $(BUILD_DIR)/gfx/Gen3/Open_Wagon/Cargo/%_4x1.png 
	@echo [GFX] $@
	@$(PYTHON) tools/stack.py --output $@ $^

# --- Gen3 Boxcar --------------------------------------------------------------

GEN3_BOXCAR_FILES = \
	$(BUILD_DIR)/gfx/Gen3_Boxcar_Standard.png

$(BUILD_DIR)/gfx/Gen3/Boxcar/Standard.png: gfx/Wagons/Gen3/Boxcar/Standard/Closed.png gfx/Wagons/Gen3/Boxcar/Standard/Open.png
	@echo [GFX] $@
	@$(PYTHON) tools/concat.py --output $@ --axis 1 $< $^

$(BUILD_DIR)/gfx/Gen3_Boxcar_%.png: $(BUILD_DIR)/gfx/Gen3/Boxcar/%.png
	@echo [GFX] $@
	@$(PYTHON) tools/stack.py --output $@ $^

# --- Gen2 Tanker --------------------------------------------------------------

GEN3_TANKER_FILES = \
	$(BUILD_DIR)/gfx/Gen3_Tanker_Standard.png \
	$(BUILD_DIR)/gfx/Gen3_Tanker_Milk.png \
	$(BUILD_DIR)/gfx/Gen3_Tanker_Oil.png \

# $(BUILD_DIR)/gfx/Gen3/Tanker/Cargo/%_4x1.png: gfx/Wagons/Gen3/Tanker/Cargo/%.png
# 	@echo [GFX] $@
# 	@$(PYTHON) tools/concat.py --output $@ --axis 0 $< $< $< $<

$(BUILD_DIR)/gfx/Gen3_Tanker_%.png: gfx/Wagons/Gen2/Tanker/Layer1.png gfx/Wagons/Gen3/Tanker/Cargo/%.png
	@echo [GFX] $@
	@$(PYTHON) tools/stack.py --output $@ $^

# --- GFX ----------------------------------------------------------------------

GFX_FILES = \
	$(GEN1_FLAT_WAGON_FILES) \
	$(GEN1_OPEN_WAGON_FILES) \
	$(GEN1_BOXCAR_FILES) \
	$(GEN1_TANKER_FILES) \
	$(GEN2_FLAT_WAGON_FILES) \
	$(GEN2_OPEN_WAGON_FILES) \
	$(GEN2_LIDDED_WAGON_FILES) \
	$(GEN2_BOXCAR_FILES) \
	$(GEN2_TANKER_FILES) \
	$(GEN3_FLAT_WAGON_FILES) \
	$(GEN3_OPEN_WAGON_FILES) \
	$(GEN3_BOXCAR_FILES)